version: '3.8'  # Using a more recent Compose file version

services:

  pg_admin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    depends_on:
      - db_postgres
    networks:
      - postgres_network

  db_postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres_network

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge